name: nilaway
on:
  push:
    tags:
      - v*
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  nilaway:
    name: nilaway
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1 https://github.com/actions/checkout/releases/tag/v6.0.1
      - uses: actions/setup-go@a5f9b05d2d216f63e13859e0d847461041025775 # v5.6.0 https://github.com/actions/setup-go/releases/tag/v5.6.0
        with:
          go-version: 1.25.x
      - name: install nilaway
        run: go install go.uber.org/nilaway/cmd/nilaway@latest
      - name: run nilaway
        run: nilaway ./...
